# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: facade.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'facade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import logging_pb2 as logging__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66\x61\x63\x61\x64\x65.proto\x12\x06\x66\x61\x63\x61\x64\x65\x1a\rlogging.proto2\x85\x01\n\rFacadeService\x12\x39\n\x0cWriteMessage\x12\x13.logging.LogRequest\x1a\x14.logging.LogResponse\x12\x39\n\x0cShowMessages\x12\x13.logging.GetRequest\x1a\x14.logging.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'facade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FACADESERVICE']._serialized_start=40
  _globals['_FACADESERVICE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
